# Generated by Django 5.2.8 on 2025-11-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(unique=True)),
                ('full_name', models.CharField(null=True)),
                ('comment', models.TextField(max_length=150, null=True)),
            ],
        ),
    ]
