# Generated by Django 5.2.8 on 2025-11-15 21:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('status', models.CharField(choices=[('CREATED', 'Создана'), ('Completed', 'Завершена'), ('Launched', 'Запущена')])),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.message')),
                ('recipients', models.ManyToManyField(to='mailing.client')),
            ],
        ),
    ]
